services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
      args:
        JAR_NAME: /*%= normalize(data.basicData.name) %*//*% if (data.basicData.version) { %*/-/*%= data.basicData.version %*//*% } %*/
    container_name: /*%= normalizeKebabCase(data.basicData.name) %*/-server
    /*% if (feature.D_C_Geoserver || feature.D_C_Postgres ) { %*/
    depends_on:
      /*% if (feature.D_C_Geoserver) { %*/
      - geoserver
      /*% } %*/
      /*% if (feature.D_C_Postgres) { %*/
      - postgres
      /*% } %*/
    /*% } %*/
    networks:
      - local
    restart: unless-stopped
    ports:
      - '/*%= getExtraConfigFromSpec(data, 'server_deploy_port', '9001') %*/:/*%= getExtraConfigFromSpec(data, 'server_deploy_port', '9001') %*/'
  client:
    build:
      context: ../client
      dockerfile: ../client/deploy/Dockerfile
    container_name: /*%= normalizeKebabCase(data.basicData.name) %*/-client
    networks:
      - local
    restart: unless-stopped
    /*% if (!feature.D_C_Nginx) { %*/
    ports:
      - '1080:80'
    /*% } %*/

  /*% if (feature.D_C_Postgres) { %*/
  postgres:
    container_name: ${PG_CONTAINER_NAME}
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
      POSTGRES_MULTIPLE_EXTENSIONS: ${POSTGRES_MULTIPLE_EXTENSIONS}
      POSTGRES_RUN_AS_ROOT: ${POSTGRES_RUN_AS_ROOT}
    volumes:
      - postgres:/data/postgres
    networks:
      - local
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "PGPASSWORD=${POSTGRES_PASSWORD} pg_isready -h 127.0.0.1 -U ${POSTGRES_USER} -d ${POSTGRES_DB}"

  /*% } %*/

  /*% if (feature.MV_Processes) { %*/
  py-qgis-wps:
    image: 3liz/qgis-wps:3.28
    container_name: qgis-wps
    user: root
    depends_on:
      - redis
    environment:
      QGSWPS_SERVER_PARALLELPROCESSES: ${QGSWPS_SERVER_PARALLELPROCESSES}
      QGSWPS_SERVER_LOGSTORAGE: REDIS
      QGSWPS_SERVER_ADMIN_REALM: '+lvm+'
      QGSWPS_SERVER_ENABLE_JOB_REALM: 'yes'
      QGSWPS_REDIS_HOST: redis
      QGSWPS_PROCESSING_PROVIDERS_MODULE_PATH: /processing
      QGSWPS_CACHE_ROOTDIR: /projects
      QGSWPS_SERVER_WORKDIR: /results
      QGSWPS_SERVER_HTTP_PROXY: 'yes'
      QGSWPS_SERVER_PROXY_URL: ${QGSWPS_SERVER_PROXY_URL}
      QGSWPS_LOGLEVEL: ${QGSWPS_LOGLEVEL}
      QGSWPS_GEOSERVER_URL: ${QGSWPS_GEOSERVER_URL}
      QGSWPS_SERVER_RESPONSE_EXPIRATION: 3600
      QGSWPS_SERVER_RESULTS_MAP_URI: /results/
      QGSWPS_SERVER_OWS_SERVICE_URL: ${QGSWPS_SERVER_OWS_SERVICE_URL}
      QGSWPS_SERVER_RESTARTMON: /processing/models
      QGSWPS_USER: ${QGSWPS_USER}
      QGSWPS_DB_NAME: ${QGSWPS_DB_NAME}
      QGSWPS_DB_HOST: ${QGSWPS_DB_HOST}
      QGSWPS_DB_PORT: ${QGSWPS_DB_PORT}
      QGSWPS_DB_USER: ${QGSWPS_DB_USER}
      QGSWPS_DB_PASSWORD: ${QGSWPS_DB_PASSWORD}
    volumes:
      - "../qgis/processing:/processing"
      - ${QGSWPS_MODELS_PATH}:/processing/models
      - projects:/projects
      - results:/results
      - ${CESGA_DIR}:/cesga
    networks:
      - local
    restart: unless-stopped
    ports:
      - "8888:8080"

  py-qgis-server:
    image: 3liz/qgis-map-server:3.40
    container_name: qgis-server
    environment:
      QGSRV_SERVER_WORKERS: ${QGSRV_SERVER_WORKERS}
      QGSWPS_SERVER_HTTP_PROXY: 'yes'
      QGSWPS_SERVER_PROXY_URL: ${QGSRV_SERVER_PROXY_URL}
      QGSRV_LOGGING_LEVEL: ${QGSRV_LOGGING_LEVEL}
      QGSRV_CACHE_ROOTDIR: /results/
      QGSRV_CACHE_STRICT_CHECK: 'no'
    volumes:
      - results:/results
      - ${CESGA_DIR}:/cesga
    networks:
      - local
    restart: unless-stopped
    ports:
      - "8082:8080"

  redis:
    container_name: qgis-redis
    image: redis:4
    networks:
      - local
    restart: unless-stopped
  /*% } %*/

  /*% if (feature.D_C_Geoserver) { %*/
  geoserver:
    container_name: ${GEOSERVER_CONTAINER_NAME}
    image: docker.osgeo.org/geoserver:2.24.1
    environment:
      - CORS_ENABLED=${GEOSERVER_CORS_ENABLED}
      - INSTALL_EXTENSIONS=${GEOSERVER_INSTALL_EXTENSIONS}
      - EXTRA_JAVA_OPTS=${GEOSERVER_EXTRA_JAVA_OPTS}
      - GEOSERVER_CSRF_WHITELIST=${GEOSERVER_CSRF_WHITELIST}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    volumes:
      - /opt/ci/deployments/geoserver/data/:/opt/geoserver_data:Z
      - /opt/ci/deployments/geoserver/additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    networks:
      - local
    ports:
      - "8080:8080"
    restart: unless-stopped

  /*% } %*/
  /*% if (feature.D_C_Nginx) { %*/
  nginx:
    container_name: ${NGINX_CONTAINER_NAME}
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    networks:
      - local
    volumes:
      - ../client/:/app/client/
    ports:
      - "80:80"
    /*% if (feature.D_C_Geoserver) { %*/
    depends_on:
      - geoserver
    /*% } %*/
    restart: unless-stopped

  /*% } %*/
volumes:
/*% if (feature.D_C_Postgres) { %*/
  postgres:
    external: false
/*% } %*/
/*% if (feature.MV_Processes) { %*/
  results:
    external: false
  projects:
    external: false
  models:
    external: false
/*% } %*/
networks:
  local:
    driver: bridge
